/**
 * Deutsche Kfz-Kennzeichen-Unterscheidungszeichen (KBA-Liste).
 *
 * Stand 2024 — aktuelle und gängige historische Codes. Die Liste deckt
 * alle Bundesländer-, Stadt- und Landkreis-Codes ab, die im KBA-
 * Verzeichnis geführt werden.
 *
 * Falls ein Code fehlt: einfach unten an die Liste anhängen.
 */

export const KFZ_KREIS_CODES = [
  { code: "A",   region: "Augsburg" },
  { code: "AA",  region: "Ostalbkreis (Aalen)" },
  { code: "AB",  region: "Aschaffenburg" },
  { code: "ABG", region: "Altenburger Land" },
  { code: "ABI", region: "Anhalt-Bitterfeld" },
  { code: "AC",  region: "Aachen / StädteRegion Aachen" },
  { code: "AE",  region: "Auerbach (Vogtlandkreis)" },
  { code: "AH",  region: "Ahaus (Borken)" },
  { code: "AIB", region: "Bad Aibling (Rosenheim)" },
  { code: "AIC", region: "Aichach-Friedberg" },
  { code: "AK",  region: "Altenkirchen (Westerwald)" },
  { code: "AL",  region: "Altmarkkreis Salzwedel" },
  { code: "ALF", region: "Alfeld (Hildesheim)" },
  { code: "ALZ", region: "Alzenau (Aschaffenburg)" },
  { code: "AM",  region: "Amberg" },
  { code: "AN",  region: "Ansbach" },
  { code: "ANA", region: "Annaberg (Erzgebirgskreis)" },
  { code: "ANG", region: "Angermünde (Uckermark)" },
  { code: "ANK", region: "Anklam (Vorpommern-Greifswald)" },
  { code: "AÖ",  region: "Altötting" },
  { code: "AP",  region: "Weimarer Land (Apolda)" },
  { code: "APD", region: "Apolda" },
  { code: "AR",  region: "Arnsberg (Hochsauerlandkreis)" },
  { code: "ARN", region: "Arnstadt (Ilm-Kreis)" },
  { code: "ART", region: "Artern (Kyffhäuserkreis)" },
  { code: "AS",  region: "Amberg-Sulzbach" },
  { code: "ASL", region: "Aschersleben (Salzlandkreis)" },
  { code: "ASZ", region: "Aue-Schwarzenberg (Erzgebirgskreis)" },
  { code: "AT",  region: "Altena (Märkischer Kreis)" },
  { code: "AU",  region: "Aue (Erzgebirgskreis)" },
  { code: "AUR", region: "Aurich" },
  { code: "AW",  region: "Ahrweiler" },
  { code: "AZ",  region: "Alzey-Worms" },
  { code: "AZE", region: "Anhalt-Zerbst" },

  { code: "B",   region: "Berlin" },
  { code: "BA",  region: "Bamberg" },
  { code: "BAD", region: "Baden-Baden" },
  { code: "BAR", region: "Barnim" },
  { code: "BB",  region: "Böblingen" },
  { code: "BBG", region: "Bernburg (Salzlandkreis)" },
  { code: "BC",  region: "Biberach" },
  { code: "BCH", region: "Buchen (Neckar-Odenwald-Kreis)" },
  { code: "BED", region: "Brand-Erbisdorf" },
  { code: "BER", region: "Bernau (Barnim)" },
  { code: "BF",  region: "Burgsteinfurt (Steinfurt)" },
  { code: "BGD", region: "Berchtesgadener Land" },
  { code: "BGL", region: "Berchtesgadener Land" },
  { code: "BH",  region: "Bühl (Rastatt)" },
  { code: "BI",  region: "Bielefeld" },
  { code: "BID", region: "Biedenkopf (Marburg-Biedenkopf)" },
  { code: "BIN", region: "Bingen (Mainz-Bingen)" },
  { code: "BIR", region: "Birkenfeld" },
  { code: "BIT", region: "Eifelkreis Bitburg-Prüm" },
  { code: "BIW", region: "Bautzen-Wartha" },
  { code: "BK",  region: "Börde" },
  { code: "BKS", region: "Bernkastel-Kues" },
  { code: "BL",  region: "Zollernalbkreis (Balingen)" },
  { code: "BLB", region: "Bad Berleburg (Siegen-Wittgenstein)" },
  { code: "BLK", region: "Burgenlandkreis" },
  { code: "BM",  region: "Rhein-Erft-Kreis (Bergheim)" },
  { code: "BN",  region: "Bonn" },
  { code: "BNA", region: "Borna (Leipzig)" },
  { code: "BO",  region: "Bochum" },
  { code: "BOG", region: "Bogen (Straubing-Bogen)" },
  { code: "BOH", region: "Bocholt (Borken)" },
  { code: "BOR", region: "Borken" },
  { code: "BOT", region: "Bottrop" },
  { code: "BRA", region: "Brake (Wesermarsch)" },
  { code: "BRB", region: "Brandenburg an der Havel" },
  { code: "BRG", region: "Burg (Jerichower Land)" },
  { code: "BRK", region: "Bad Brückenau" },
  { code: "BRL", region: "Berleburg" },
  { code: "BRV", region: "Bremervörde (Rotenburg/Wümme)" },
  { code: "BS",  region: "Braunschweig" },
  { code: "BSB", region: "Bersenbrück (Osnabrück)" },
  { code: "BSK", region: "Beeskow (Oder-Spree)" },
  { code: "BT",  region: "Bayreuth" },
  { code: "BTF", region: "Bitterfeld (Anhalt-Bitterfeld)" },
  { code: "BÜD", region: "Büdingen (Wetteraukreis)" },
  { code: "BÜR", region: "Büren (Paderborn)" },
  { code: "BÜS", region: "Büsingen am Hochrhein" },
  { code: "BÜZ", region: "Bützow (Rostock)" },
  { code: "BWL", region: "Land Baden-Württemberg" },
  { code: "BYL", region: "Land Bayern" },
  { code: "BZ",  region: "Bautzen" },

  { code: "C",   region: "Chemnitz" },
  { code: "CAS", region: "Castrop-Rauxel" },
  { code: "CB",  region: "Cottbus" },
  { code: "CE",  region: "Celle" },
  { code: "CHA", region: "Cham" },
  { code: "CLP", region: "Cloppenburg" },
  { code: "CLZ", region: "Clausthal-Zellerfeld" },
  { code: "CO",  region: "Coburg" },
  { code: "COC", region: "Cochem-Zell" },
  { code: "COE", region: "Coesfeld" },
  { code: "CR",  region: "Crailsheim (Schwäbisch Hall)" },
  { code: "CUX", region: "Cuxhaven" },
  { code: "CW",  region: "Calw" },

  { code: "D",   region: "Düsseldorf" },
  { code: "DA",  region: "Darmstadt" },
  { code: "DAH", region: "Dachau" },
  { code: "DAN", region: "Lüchow-Dannenberg" },
  { code: "DAU", region: "Vulkaneifel (Daun)" },
  { code: "DBR", region: "Bad Doberan (Rostock)" },
  { code: "DD",  region: "Dresden" },
  { code: "DE",  region: "Dessau-Roßlau" },
  { code: "DEG", region: "Deggendorf" },
  { code: "DEL", region: "Delmenhorst" },
  { code: "DGF", region: "Dingolfing-Landau" },
  { code: "DH",  region: "Diepholz" },
  { code: "DI",  region: "Dieburg (Darmstadt-Dieburg)" },
  { code: "DIL", region: "Dillenburg (Lahn-Dill-Kreis)" },
  { code: "DIN", region: "Dinkelsbühl (Ansbach)" },
  { code: "DIZ", region: "Diez (Rhein-Lahn-Kreis)" },
  { code: "DKB", region: "Dinkelsbühl" },
  { code: "DL",  region: "Döbeln" },
  { code: "DLG", region: "Dillingen an der Donau" },
  { code: "DM",  region: "Demmin (Mecklenburgische Seenplatte)" },
  { code: "DN",  region: "Düren" },
  { code: "DO",  region: "Dortmund" },
  { code: "DON", region: "Donau-Ries" },
  { code: "DT",  region: "Detmold (Lippe)" },
  { code: "DU",  region: "Duisburg" },
  { code: "DUW", region: "Bad Dürkheim" },
  { code: "DW",  region: "Dippoldiswalde (Sächsische Schweiz-Osterzgebirge)" },
  { code: "DZ",  region: "Delitzsch (Nordsachsen)" },

  { code: "E",   region: "Essen" },
  { code: "EA",  region: "Eisenach" },
  { code: "EB",  region: "Eilenburg (Nordsachsen)" },
  { code: "EBE", region: "Ebersberg" },
  { code: "EBN", region: "Ebern (Haßberge)" },
  { code: "EBS", region: "Ebermannstadt (Forchheim)" },
  { code: "ECK", region: "Eckernförde (Rendsburg-Eckernförde)" },
  { code: "ED",  region: "Erding" },
  { code: "EE",  region: "Elbe-Elster" },
  { code: "EF",  region: "Erfurt" },
  { code: "EG",  region: "Eggenfelden (Rottal-Inn)" },
  { code: "EH",  region: "Eisenhüttenstadt" },
  { code: "EI",  region: "Eichstätt" },
  { code: "EIC", region: "Eichsfeld" },
  { code: "EIL", region: "Mansfeld-Südharz (Eisleben)" },
  { code: "EIS", region: "Eisenberg (Saale-Holzland-Kreis)" },
  { code: "EL",  region: "Emsland" },
  { code: "EM",  region: "Emmendingen" },
  { code: "EMD", region: "Emden" },
  { code: "EMS", region: "Rhein-Lahn-Kreis (Bad Ems)" },
  { code: "EN",  region: "Ennepe-Ruhr-Kreis" },
  { code: "ER",  region: "Erlangen" },
  { code: "ERB", region: "Odenwaldkreis (Erbach)" },
  { code: "ERH", region: "Erlangen-Höchstadt" },
  { code: "ERK", region: "Erkelenz (Heinsberg)" },
  { code: "ERZ", region: "Erzgebirgskreis" },
  { code: "ES",  region: "Esslingen" },
  { code: "ESB", region: "Eschenbach (Neustadt/Waldnaab)" },
  { code: "ESW", region: "Werra-Meißner-Kreis (Eschwege)" },
  { code: "EU",  region: "Euskirchen" },

  { code: "F",   region: "Frankfurt am Main" },
  { code: "FB",  region: "Wetteraukreis (Friedberg)" },
  { code: "FD",  region: "Fulda" },
  { code: "FDB", region: "Friedberg (Bayern)" },
  { code: "FDS", region: "Freudenstadt" },
  { code: "FF",  region: "Frankfurt (Oder)" },
  { code: "FFB", region: "Fürstenfeldbruck" },
  { code: "FG",  region: "Mittelsachsen (Freiberg)" },
  { code: "FI",  region: "Finsterwalde (Elbe-Elster)" },
  { code: "FL",  region: "Flensburg" },
  { code: "FLÖ", region: "Flöha (Mittelsachsen)" },
  { code: "FN",  region: "Bodenseekreis (Friedrichshafen)" },
  { code: "FO",  region: "Forchheim" },
  { code: "FR",  region: "Breisgau-Hochschwarzwald (Freiburg)" },
  { code: "FRG", region: "Freyung-Grafenau" },
  { code: "FRI", region: "Friesland" },
  { code: "FRW", region: "Bad Freienwalde (Märkisch-Oderland)" },
  { code: "FS",  region: "Freising" },
  { code: "FT",  region: "Frankenthal (Pfalz)" },
  { code: "FTL", region: "Freital (Sächsische Schweiz-Osterzgebirge)" },
  { code: "FÜ",  region: "Fürth" },
  { code: "FÜS", region: "Füssen (Ostallgäu)" },
  { code: "FW",  region: "Fürstenwalde (Oder-Spree)" },

  { code: "G",   region: "Gera" },
  { code: "GA",  region: "Gardelegen (Altmarkkreis Salzwedel)" },
  { code: "GAN", region: "Gandersheim (Northeim)" },
  { code: "GAP", region: "Garmisch-Partenkirchen" },
  { code: "GC",  region: "Glauchau (Zwickau)" },
  { code: "GD",  region: "Schwäbisch Gmünd (Ostalbkreis)" },
  { code: "GDB", region: "Gadebusch (Nordwestmecklenburg)" },
  { code: "GE",  region: "Gelsenkirchen" },
  { code: "GEL", region: "Geldern (Kleve)" },
  { code: "GEO", region: "Bad Gandersheim" },
  { code: "GER", region: "Germersheim" },
  { code: "GF",  region: "Gifhorn" },
  { code: "GG",  region: "Groß-Gerau" },
  { code: "GHA", region: "Geithain (Leipzig)" },
  { code: "GHC", region: "Gräfenhainichen (Wittenberg)" },
  { code: "GI",  region: "Gießen" },
  { code: "GK",  region: "Geilenkirchen (Heinsberg)" },
  { code: "GL",  region: "Rheinisch-Bergischer Kreis" },
  { code: "GLA", region: "Gladbeck (Recklinghausen)" },
  { code: "GM",  region: "Oberbergischer Kreis (Gummersbach)" },
  { code: "GMN", region: "Grimmen (Vorpommern-Rügen)" },
  { code: "GN",  region: "Main-Kinzig-Kreis (Gelnhausen)" },
  { code: "GNT", region: "Genthin (Jerichower Land)" },
  { code: "GÖ",  region: "Göttingen" },
  { code: "GP",  region: "Göppingen" },
  { code: "GR",  region: "Görlitz" },
  { code: "GRA", region: "Grafenau (Freyung-Grafenau)" },
  { code: "GRH", region: "Großenhain (Meißen)" },
  { code: "GRI", region: "Griesbach (Passau)" },
  { code: "GRM", region: "Grimma (Leipzig)" },
  { code: "GRZ", region: "Greiz" },
  { code: "GS",  region: "Goslar" },
  { code: "GT",  region: "Gütersloh" },
  { code: "GTH", region: "Gotha" },
  { code: "GUB", region: "Guben (Spree-Neiße)" },
  { code: "GUN", region: "Gunzenhausen (Weißenburg-Gunzenhausen)" },
  { code: "GV",  region: "Geldern" },
  { code: "GVM", region: "Grevesmühlen (Nordwestmecklenburg)" },
  { code: "GW",  region: "Greifswald (Vorpommern-Greifswald)" },
  { code: "GZ",  region: "Günzburg" },

  { code: "H",   region: "Hannover" },
  { code: "HA",  region: "Hagen" },
  { code: "HAB", region: "Hammelburg (Bad Kissingen)" },
  { code: "HAL", region: "Halle (Saale)" },
  { code: "HAM", region: "Hamm" },
  { code: "HAS", region: "Haßberge" },
  { code: "HB",  region: "Bremen / Bremerhaven" },
  { code: "HBN", region: "Hildburghausen" },
  { code: "HBS", region: "Halberstadt (Harz)" },
  { code: "HC",  region: "Hohenmölsen (Burgenlandkreis)" },
  { code: "HCH", region: "Hechingen (Zollernalbkreis)" },
  { code: "HD",  region: "Heidelberg / Rhein-Neckar-Kreis" },
  { code: "HDH", region: "Heidenheim" },
  { code: "HDL", region: "Haldensleben (Börde)" },
  { code: "HE",  region: "Helmstedt" },
  { code: "HEB", region: "Hersbruck (Nürnberger Land)" },
  { code: "HEF", region: "Hersfeld-Rotenburg" },
  { code: "HEI", region: "Dithmarschen (Heide)" },
  { code: "HER", region: "Herne" },
  { code: "HET", region: "Hettstedt (Mansfeld-Südharz)" },
  { code: "HF",  region: "Herford" },
  { code: "HG",  region: "Hochtaunuskreis (Bad Homburg)" },
  { code: "HGN", region: "Hagenow (Ludwigslust-Parchim)" },
  { code: "HGW", region: "Hansestadt Greifswald" },
  { code: "HH",  region: "Hamburg" },
  { code: "HI",  region: "Hildesheim" },
  { code: "HIG", region: "Heiligenstadt (Eichsfeld)" },
  { code: "HIP", region: "Hilpoltstein (Roth)" },
  { code: "HK",  region: "Heidekreis" },
  { code: "HL",  region: "Lübeck" },
  { code: "HM",  region: "Hameln-Pyrmont" },
  { code: "HMÜ", region: "Hannoversch Münden (Göttingen)" },
  { code: "HN",  region: "Heilbronn" },
  { code: "HO",  region: "Hof" },
  { code: "HOG", region: "Hofgeismar (Kassel)" },
  { code: "HOH", region: "Hofheim (Haßberge)" },
  { code: "HOL", region: "Holzminden" },
  { code: "HOM", region: "Saarpfalz-Kreis (Homburg)" },
  { code: "HOR", region: "Horb am Neckar (Freudenstadt)" },
  { code: "HOT", region: "Hohenstein-Ernstthal (Zwickau)" },
  { code: "HP",  region: "Bergstraße (Heppenheim)" },
  { code: "HR",  region: "Schwalm-Eder-Kreis" },
  { code: "HRO", region: "Rostock (Hansestadt)" },
  { code: "HS",  region: "Heinsberg" },
  { code: "HSK", region: "Hochsauerlandkreis" },
  { code: "HST", region: "Stralsund (Vorpommern-Rügen)" },
  { code: "HU",  region: "Hanau (Main-Kinzig-Kreis)" },
  { code: "HV",  region: "Havelberg (Stendal)" },
  { code: "HVL", region: "Havelland" },
  { code: "HWI", region: "Hagenow-Wittenburg" },
  { code: "HX",  region: "Höxter" },
  { code: "HY",  region: "Hoyerswerda (Bautzen)" },
  { code: "HZ",  region: "Harz (Wernigerode)" },

  { code: "IGB", region: "St. Ingbert (Saarpfalz-Kreis)" },
  { code: "IK",  region: "Ilm-Kreis" },
  { code: "IL",  region: "Ilmenau (Ilm-Kreis)" },
  { code: "ILL", region: "Illertissen (Neu-Ulm)" },
  { code: "IN",  region: "Ingolstadt" },
  { code: "IZ",  region: "Steinburg (Itzehoe)" },

  { code: "J",   region: "Jena" },
  { code: "JE",  region: "Jessen (Wittenberg)" },
  { code: "JL",  region: "Jerichower Land" },

  { code: "K",   region: "Köln" },
  { code: "KA",  region: "Karlsruhe" },
  { code: "KB",  region: "Waldeck-Frankenberg (Korbach)" },
  { code: "KC",  region: "Kronach" },
  { code: "KE",  region: "Kempten (Allgäu)" },
  { code: "KEH", region: "Kelheim" },
  { code: "KEL", region: "Kehl (Ortenaukreis)" },
  { code: "KEM", region: "Kemnath (Tirschenreuth)" },
  { code: "KF",  region: "Kaufbeuren" },
  { code: "KG",  region: "Bad Kissingen" },
  { code: "KH",  region: "Bad Kreuznach" },
  { code: "KI",  region: "Kiel" },
  { code: "KIB", region: "Donnersbergkreis (Kirchheimbolanden)" },
  { code: "KK",  region: "Viersen (Kempen-Krefeld)" },
  { code: "KL",  region: "Kaiserslautern" },
  { code: "KLE", region: "Kleve" },
  { code: "KLZ", region: "Klötze (Altmarkkreis Salzwedel)" },
  { code: "KM",  region: "Kamenz (Bautzen)" },
  { code: "KN",  region: "Konstanz" },
  { code: "KO",  region: "Koblenz" },
  { code: "KÖN", region: "Königshofen (Rhön-Grabfeld)" },
  { code: "KÖT", region: "Köthen (Anhalt-Bitterfeld)" },
  { code: "KÖZ", region: "Bad Kötzting (Cham)" },
  { code: "KR",  region: "Krefeld" },
  { code: "KRU", region: "Krumbach (Günzburg)" },
  { code: "KS",  region: "Kassel" },
  { code: "KT",  region: "Kitzingen" },
  { code: "KU",  region: "Kulmbach" },
  { code: "KÜN", region: "Hohenlohekreis (Künzelsau)" },
  { code: "KUS", region: "Kusel" },
  { code: "KW",  region: "Königs Wusterhausen (Dahme-Spreewald)" },
  { code: "KY",  region: "Kyritz (Ostprignitz-Ruppin)" },
  { code: "KYF", region: "Kyffhäuserkreis" },

  { code: "L",   region: "Leipzig" },
  { code: "LA",  region: "Landshut" },
  { code: "LAN", region: "Landau (Pfalz)" },
  { code: "LAU", region: "Nürnberger Land (Lauf)" },
  { code: "LB",  region: "Ludwigsburg" },
  { code: "LBS", region: "Lobenstein (Saale-Orla-Kreis)" },
  { code: "LBZ", region: "Lübz (Ludwigslust-Parchim)" },
  { code: "LC",  region: "Luckau (Dahme-Spreewald)" },
  { code: "LD",  region: "Landau in der Pfalz" },
  { code: "LDK", region: "Lahn-Dill-Kreis" },
  { code: "LDS", region: "Dahme-Spreewald" },
  { code: "LEO", region: "Leonberg (Böblingen)" },
  { code: "LER", region: "Leer (Ostfriesland)" },
  { code: "LEV", region: "Leverkusen" },
  { code: "LG",  region: "Lüneburg" },
  { code: "LH",  region: "Lüdinghausen (Coesfeld)" },
  { code: "LI",  region: "Lindau (Bodensee)" },
  { code: "LIB", region: "Bad Liebenwerda (Elbe-Elster)" },
  { code: "LIF", region: "Lichtenfels" },
  { code: "LIP", region: "Lippstadt (Soest)" },
  { code: "LL",  region: "Landsberg am Lech" },
  { code: "LM",  region: "Limburg-Weilburg" },
  { code: "LN",  region: "Lübben (Dahme-Spreewald)" },
  { code: "LÖ",  region: "Lörrach" },
  { code: "LOS", region: "Oder-Spree" },
  { code: "LP",  region: "Lippstadt" },
  { code: "LR",  region: "Lahr (Ortenaukreis)" },
  { code: "LRO", region: "Landkreis Rostock" },
  { code: "LSA", region: "Land Sachsen-Anhalt" },
  { code: "LSN", region: "Land Sachsen" },
  { code: "LU",  region: "Ludwigshafen am Rhein" },
  { code: "LUP", region: "Ludwigslust-Parchim" },

  { code: "M",   region: "München" },
  { code: "MA",  region: "Mannheim" },
  { code: "MAB", region: "Marienberg (Erzgebirgskreis)" },
  { code: "MAI", region: "Mainburg (Kelheim)" },
  { code: "MAK", region: "Marktredwitz (Wunsiedel)" },
  { code: "MAL", region: "Mallersdorf (Straubing-Bogen)" },
  { code: "MB",  region: "Miesbach" },
  { code: "MC",  region: "Malchin (Mecklenburgische Seenplatte)" },
  { code: "MD",  region: "Magdeburg" },
  { code: "ME",  region: "Mettmann" },
  { code: "MED", region: "Medebach (Hochsauerlandkreis)" },
  { code: "MEG", region: "Meiningen (Schmalkalden-Meiningen)" },
  { code: "MEI", region: "Meißen" },
  { code: "MEK", region: "Mittlerer Erzgebirgskreis" },
  { code: "MEL", region: "Melle (Osnabrück)" },
  { code: "MEP", region: "Meppen (Emsland)" },
  { code: "MER", region: "Saalekreis (Merseburg)" },
  { code: "MES", region: "Meschede (Hochsauerlandkreis)" },
  { code: "MG",  region: "Mönchengladbach" },
  { code: "MH",  region: "Mülheim an der Ruhr" },
  { code: "MHL", region: "Mühlhausen (Unstrut-Hainich-Kreis)" },
  { code: "MI",  region: "Minden-Lübbecke" },
  { code: "MIL", region: "Miltenberg" },
  { code: "MK",  region: "Märkischer Kreis" },
  { code: "MKK", region: "Main-Kinzig-Kreis" },
  { code: "ML",  region: "Mansfeld-Südharz" },
  { code: "MM",  region: "Memmingen" },
  { code: "MN",  region: "Unterallgäu (Mindelheim)" },
  { code: "MO",  region: "Moers (Wesel)" },
  { code: "MOD", region: "Marktoberdorf (Ostallgäu)" },
  { code: "MOL", region: "Märkisch-Oderland" },
  { code: "MON", region: "Monschau (Aachen)" },
  { code: "MOS", region: "Neckar-Odenwald-Kreis (Mosbach)" },
  { code: "MQ",  region: "Merseburg-Querfurt" },
  { code: "MR",  region: "Marburg-Biedenkopf" },
  { code: "MS",  region: "Münster" },
  { code: "MSE", region: "Mecklenburgische Seenplatte" },
  { code: "MSH", region: "Mansfeld-Südharz" },
  { code: "MSP", region: "Main-Spessart" },
  { code: "MST", region: "Mecklenburg-Strelitz" },
  { code: "MTK", region: "Main-Taunus-Kreis" },
  { code: "MTL", region: "Muldentalkreis (Leipzig)" },
  { code: "MÜ",  region: "Mühldorf am Inn" },
  { code: "MÜB", region: "Münchberg (Hof)" },
  { code: "MÜR", region: "Müritz" },
  { code: "MVL", region: "Land Mecklenburg-Vorpommern" },
  { code: "MW",  region: "Mittweida (Mittelsachsen)" },
  { code: "MY",  region: "Mayen (Mayen-Koblenz)" },
  { code: "MYK", region: "Mayen-Koblenz" },
  { code: "MZ",  region: "Mainz / Mainz-Bingen" },
  { code: "MZG", region: "Merzig-Wadern" },

  { code: "N",   region: "Nürnberg" },
  { code: "NAB", region: "Nabburg (Schwandorf)" },
  { code: "NAI", region: "Naila (Hof)" },
  { code: "NAU", region: "Nauen (Havelland)" },
  { code: "NB",  region: "Neubrandenburg" },
  { code: "ND",  region: "Neuburg-Schrobenhausen" },
  { code: "NDH", region: "Nordhausen" },
  { code: "NE",  region: "Rhein-Kreis Neuss" },
  { code: "NEA", region: "Neustadt an der Aisch-Bad Windsheim" },
  { code: "NEB", region: "Nebra (Burgenlandkreis)" },
  { code: "NEC", region: "Neumarkt-Sankt Veit" },
  { code: "NEN", region: "Neunburg vorm Wald (Schwandorf)" },
  { code: "NES", region: "Rhön-Grabfeld (Bad Neustadt/Saale)" },
  { code: "NEW", region: "Neustadt an der Waldnaab" },
  { code: "NF",  region: "Nordfriesland" },
  { code: "NH",  region: "Neuhaus am Rennweg (Sonneberg)" },
  { code: "NI",  region: "Nienburg/Weser" },
  { code: "NK",  region: "Neunkirchen (Saar)" },
  { code: "NM",  region: "Neumarkt in der Oberpfalz" },
  { code: "NMB", region: "Naumburg (Burgenlandkreis)" },
  { code: "NMS", region: "Neumünster" },
  { code: "NÖ",  region: "Nördlingen (Donau-Ries)" },
  { code: "NOH", region: "Grafschaft Bentheim (Nordhorn)" },
  { code: "NOL", region: "Niederschlesischer Oberlausitzkreis" },
  { code: "NOM", region: "Northeim" },
  { code: "NOR", region: "Norden (Aurich)" },
  { code: "NP",  region: "Neuruppin (Ostprignitz-Ruppin)" },
  { code: "NR",  region: "Neuwied" },
  { code: "NRW", region: "Land Nordrhein-Westfalen" },
  { code: "NU",  region: "Neu-Ulm" },
  { code: "NVP", region: "Nordvorpommern" },
  { code: "NWM", region: "Nordwestmecklenburg" },
  { code: "NY",  region: "Niesky (Görlitz)" },
  { code: "NZ",  region: "Neustrelitz (Mecklenburgische Seenplatte)" },

  { code: "OA",  region: "Oberallgäu (Sonthofen)" },
  { code: "OAL", region: "Ostallgäu (Marktoberdorf)" },
  { code: "OB",  region: "Oberhausen" },
  { code: "OBB", region: "Obernburg (Miltenberg)" },
  { code: "OBG", region: "Osterburg (Stendal)" },
  { code: "OC",  region: "Oschersleben (Börde)" },
  { code: "OCH", region: "Ochsenfurt (Würzburg)" },
  { code: "OD",  region: "Stormarn (Bad Oldesloe)" },
  { code: "OE",  region: "Olpe" },
  { code: "OF",  region: "Offenbach am Main" },
  { code: "OG",  region: "Ortenaukreis (Offenburg)" },
  { code: "OH",  region: "Ostholstein" },
  { code: "OHA", region: "Osterode am Harz (Göttingen)" },
  { code: "OHV", region: "Oberhavel" },
  { code: "OHZ", region: "Osterholz" },
  { code: "OK",  region: "Ohrekreis" },
  { code: "OL",  region: "Oldenburg (Oldenburg)" },
  { code: "OPR", region: "Ostprignitz-Ruppin" },
  { code: "OS",  region: "Osnabrück" },
  { code: "OSL", region: "Oberspreewald-Lausitz" },
  { code: "OVL", region: "Oberverlausitz" },
  { code: "OVP", region: "Ostvorpommern" },

  { code: "P",   region: "Potsdam" },
  { code: "PA",  region: "Passau" },
  { code: "PAF", region: "Pfaffenhofen an der Ilm" },
  { code: "PAN", region: "Rottal-Inn (Pfarrkirchen)" },
  { code: "PAR", region: "Parsberg (Neumarkt)" },
  { code: "PB",  region: "Paderborn" },
  { code: "PCH", region: "Parchim (Ludwigslust-Parchim)" },
  { code: "PE",  region: "Peine" },
  { code: "PEG", region: "Pegnitz (Bayreuth)" },
  { code: "PER", region: "Perleberg (Prignitz)" },
  { code: "PF",  region: "Pforzheim / Enzkreis" },
  { code: "PI",  region: "Pinneberg" },
  { code: "PIR", region: "Sächsische Schweiz-Osterzgebirge (Pirna)" },
  { code: "PL",  region: "Plauen (Vogtlandkreis)" },
  { code: "PLÖ", region: "Plön" },
  { code: "PM",  region: "Potsdam-Mittelmark" },
  { code: "PN",  region: "Pößneck (Saale-Orla-Kreis)" },
  { code: "PR",  region: "Prignitz" },
  { code: "PS",  region: "Pirmasens / Südwestpfalz" },
  { code: "PZ",  region: "Prenzlau (Uckermark)" },

  { code: "QFT", region: "Querfurt (Saalekreis)" },
  { code: "QLB", region: "Harz (Quedlinburg)" },

  { code: "R",   region: "Regensburg" },
  { code: "RA",  region: "Rastatt" },
  { code: "RC",  region: "Reichenbach (Vogtlandkreis)" },
  { code: "RD",  region: "Rendsburg-Eckernförde" },
  { code: "RE",  region: "Recklinghausen" },
  { code: "REG", region: "Regen" },
  { code: "REH", region: "Rehau (Hof)" },
  { code: "REI", region: "Riesa (Meißen)" },
  { code: "RG",  region: "Riesa-Großenhain" },
  { code: "RH",  region: "Roth" },
  { code: "RI",  region: "Schaumburg (Stadthagen)" },
  { code: "RIE", region: "Riedlingen (Biberach)" },
  { code: "RL",  region: "Rochlitz (Mittelsachsen)" },
  { code: "RM",  region: "Rostock (Land)" },
  { code: "RN",  region: "Rendsburg" },
  { code: "RO",  region: "Rosenheim" },
  { code: "ROD", region: "Roding (Cham)" },
  { code: "ROK", region: "Rockenhausen (Donnersbergkreis)" },
  { code: "ROL", region: "Rottenburg an der Laaber" },
  { code: "ROS", region: "Rostock (Land)" },
  { code: "ROT", region: "Rothenburg ob der Tauber (Ansbach)" },
  { code: "ROW", region: "Rotenburg (Wümme)" },
  { code: "RP",  region: "Land Rheinland-Pfalz" },
  { code: "RS",  region: "Remscheid" },
  { code: "RSL", region: "Roßlau (Dessau-Roßlau)" },
  { code: "RT",  region: "Reutlingen" },
  { code: "RU",  region: "Saalfeld-Rudolstadt" },
  { code: "RV",  region: "Ravensburg" },
  { code: "RW",  region: "Rottweil" },
  { code: "RZ",  region: "Herzogtum Lauenburg (Ratzeburg)" },

  { code: "S",   region: "Stuttgart" },
  { code: "SAB", region: "Saarburg (Trier-Saarburg)" },
  { code: "SAD", region: "Schwandorf" },
  { code: "SAW", region: "Altmarkkreis Salzwedel" },
  { code: "SB",  region: "Saarbrücken" },
  { code: "SBG", region: "Strasburg (Vorpommern-Greifswald)" },
  { code: "SBK", region: "Schönebeck (Salzlandkreis)" },
  { code: "SC",  region: "Schwabach" },
  { code: "SCZ", region: "Schleiz (Saale-Orla-Kreis)" },
  { code: "SDH", region: "Sondershausen (Kyffhäuserkreis)" },
  { code: "SDL", region: "Stendal" },
  { code: "SDT", region: "Schwedt (Uckermark)" },
  { code: "SE",  region: "Segeberg" },
  { code: "SEB", region: "Sebnitz (Sächsische Schweiz-Osterzgebirge)" },
  { code: "SEE", region: "Seelow (Märkisch-Oderland)" },
  { code: "SEF", region: "Sankt Goarshausen" },
  { code: "SEL", region: "Selb (Wunsiedel)" },
  { code: "SFA", region: "Soltau-Fallingbostel" },
  { code: "SFB", region: "Senftenberg (Oberspreewald-Lausitz)" },
  { code: "SFT", region: "Staßfurt (Salzlandkreis)" },
  { code: "SG",  region: "Solingen" },
  { code: "SGH", region: "Sangerhausen (Mansfeld-Südharz)" },
  { code: "SHA", region: "Schwäbisch Hall" },
  { code: "SHG", region: "Schaumburg" },
  { code: "SHK", region: "Saale-Holzland-Kreis" },
  { code: "SHL", region: "Suhl" },
  { code: "SI",  region: "Siegen-Wittgenstein" },
  { code: "SIG", region: "Sigmaringen" },
  { code: "SIM", region: "Rhein-Hunsrück-Kreis (Simmern)" },
  { code: "SK",  region: "Saalekreis" },
  { code: "SL",  region: "Schleswig-Flensburg" },
  { code: "SLE", region: "Schleiden (Euskirchen)" },
  { code: "SLF", region: "Saalfeld-Rudolstadt" },
  { code: "SLK", region: "Salzlandkreis" },
  { code: "SLN", region: "Schmölln (Altenburger Land)" },
  { code: "SLS", region: "Saarlouis" },
  { code: "SLZ", region: "Bad Salzungen (Wartburgkreis)" },
  { code: "SM",  region: "Schmalkalden-Meiningen" },
  { code: "SMÜ", region: "Schwabmünchen (Augsburg)" },
  { code: "SN",  region: "Schwerin" },
  { code: "SO",  region: "Soest" },
  { code: "SOB", region: "Schrobenhausen (Neuburg-Schrobenhausen)" },
  { code: "SOG", region: "Schongau (Weilheim-Schongau)" },
  { code: "SOK", region: "Saale-Orla-Kreis" },
  { code: "SÖM", region: "Sömmerda" },
  { code: "SON", region: "Sonneberg" },
  { code: "SP",  region: "Speyer" },
  { code: "SPB", region: "Spremberg (Spree-Neiße)" },
  { code: "SPN", region: "Spree-Neiße" },
  { code: "SR",  region: "Straubing / Straubing-Bogen" },
  { code: "ST",  region: "Steinfurt" },
  { code: "STA", region: "Starnberg" },
  { code: "STB", region: "Stollberg (Erzgebirgskreis)" },
  { code: "STD", region: "Stade" },
  { code: "STE", region: "Bad Staffelstein (Lichtenfels)" },
  { code: "STL", region: "Stollberg" },
  { code: "SU",  region: "Rhein-Sieg-Kreis" },
  { code: "SUL", region: "Sulzbach-Rosenberg (Amberg-Sulzbach)" },
  { code: "SÜW", region: "Südliche Weinstraße" },
  { code: "SW",  region: "Schweinfurt" },
  { code: "SY",  region: "Diepholz (Syke)" },
  { code: "SZ",  region: "Salzgitter" },

  { code: "TBB", region: "Main-Tauber-Kreis (Tauberbischofsheim)" },
  { code: "TDO", region: "Torgau-Oschatz" },
  { code: "TE",  region: "Tecklenburg (Steinfurt)" },
  { code: "TET", region: "Teterow (Mecklenburgische Seenplatte)" },
  { code: "TF",  region: "Teltow-Fläming" },
  { code: "TG",  region: "Torgau (Nordsachsen)" },
  { code: "TIR", region: "Tirschenreuth" },
  { code: "TÖL", region: "Bad Tölz-Wolfratshausen" },
  { code: "TO",  region: "Torgau-Oschatz" },
  { code: "TR",  region: "Trier / Trier-Saarburg" },
  { code: "TS",  region: "Traunstein" },
  { code: "TÜ",  region: "Tübingen" },
  { code: "TUT", region: "Tuttlingen" },

  { code: "UE",  region: "Uelzen" },
  { code: "UEM", region: "Ueckermünde (Vorpommern-Greifswald)" },
  { code: "UER", region: "Uecker-Randow" },
  { code: "UH",  region: "Unstrut-Hainich-Kreis" },
  { code: "UL",  region: "Ulm / Alb-Donau-Kreis" },
  { code: "UM",  region: "Uckermark" },
  { code: "UN",  region: "Unna" },
  { code: "USI", region: "Usingen (Hochtaunuskreis)" },

  { code: "V",   region: "Vogtlandkreis" },
  { code: "VAI", region: "Vaihingen an der Enz (Ludwigsburg)" },
  { code: "VB",  region: "Vogelsbergkreis" },
  { code: "VEC", region: "Vechta" },
  { code: "VER", region: "Verden (Aller)" },
  { code: "VG",  region: "Vorpommern-Greifswald" },
  { code: "VIB", region: "Vilsbiburg (Landshut)" },
  { code: "VIE", region: "Viersen" },
  { code: "VIT", region: "Viechtach (Regen)" },
  { code: "VK",  region: "Völklingen (Saarbrücken)" },
  { code: "VOH", region: "Vohenstrauß (Neustadt/Waldnaab)" },
  { code: "VR",  region: "Vorpommern-Rügen" },
  { code: "VS",  region: "Schwarzwald-Baar-Kreis" },

  { code: "W",   region: "Wuppertal" },
  { code: "WA",  region: "Waldeck (Frankenberg)" },
  { code: "WAF", region: "Warendorf" },
  { code: "WAK", region: "Wartburgkreis" },
  { code: "WAN", region: "Wanne-Eickel" },
  { code: "WAT", region: "Wattenscheid" },
  { code: "WB",  region: "Wittenberg" },
  { code: "WBS", region: "Worbis (Eichsfeld)" },
  { code: "WD",  region: "Wiedenbrück (Gütersloh)" },
  { code: "WDA", region: "Werdau (Zwickau)" },
  { code: "WE",  region: "Weimar" },
  { code: "WEL", region: "Limburg-Weilburg (Weilburg)" },
  { code: "WEN", region: "Weiden in der Oberpfalz" },
  { code: "WER", region: "Wertheim (Main-Tauber-Kreis)" },
  { code: "WES", region: "Wesel" },
  { code: "WF",  region: "Wolfenbüttel" },
  { code: "WHV", region: "Wilhelmshaven" },
  { code: "WI",  region: "Wiesbaden" },
  { code: "WIL", region: "Bernkastel-Wittlich" },
  { code: "WIS", region: "Wismar (Nordwestmecklenburg)" },
  { code: "WIT", region: "Witten (Ennepe-Ruhr-Kreis)" },
  { code: "WIZ", region: "Witzenhausen (Werra-Meißner)" },
  { code: "WK",  region: "Wittstock (Ostprignitz-Ruppin)" },
  { code: "WL",  region: "Harburg (Winsen/Luhe)" },
  { code: "WLG", region: "Wolgast (Vorpommern-Greifswald)" },
  { code: "WM",  region: "Weilheim-Schongau" },
  { code: "WMS", region: "Wolmirstedt (Börde)" },
  { code: "WN",  region: "Rems-Murr-Kreis (Waiblingen)" },
  { code: "WND", region: "Sankt Wendel" },
  { code: "WO",  region: "Worms" },
  { code: "WOB", region: "Wolfsburg" },
  { code: "WOH", region: "Wolfhagen (Kassel)" },
  { code: "WOL", region: "Wolfen (Anhalt-Bitterfeld)" },
  { code: "WOR", region: "Worbis" },
  { code: "WR",  region: "Wernigerode (Harz)" },
  { code: "WRN", region: "Waren (Müritz)" },
  { code: "WS",  region: "Wasserburg am Inn (Rosenheim)" },
  { code: "WSF", region: "Weißenfels (Burgenlandkreis)" },
  { code: "WST", region: "Westerstede (Ammerland)" },
  { code: "WSW", region: "Wesermünde (Cuxhaven)" },
  { code: "WT",  region: "Waldshut" },
  { code: "WTM", region: "Wittmund" },
  { code: "WÜ",  region: "Würzburg" },
  { code: "WUG", region: "Weißenburg-Gunzenhausen" },
  { code: "WUN", region: "Wunsiedel im Fichtelgebirge" },
  { code: "WUR", region: "Wurzen (Leipzig)" },
  { code: "WW",  region: "Westerwaldkreis" },
  { code: "WZ",  region: "Weißwasser (Görlitz)" },
  { code: "WZL", region: "Wanzleben (Börde)" },

  { code: "Y",   region: "Bundeswehr" },
  { code: "Z",   region: "Zwickau" },
  { code: "ZE",  region: "Zerbst (Anhalt-Bitterfeld)" },
  { code: "ZEL", region: "Zell an der Mosel (Cochem-Zell)" },
  { code: "ZI",  region: "Zittau (Görlitz)" },
  { code: "ZP",  region: "Zossen (Teltow-Fläming)" },
  { code: "ZR",  region: "Zeulenroda (Greiz)" },
  { code: "ZW",  region: "Zweibrücken" },
  { code: "ZZ",  region: "Zeitz (Burgenlandkreis)" },
];

const KFZ_KREIS_SET = new Set(KFZ_KREIS_CODES.map(k => k.code));

export function isValidKreisCode(code) {
  return KFZ_KREIS_SET.has((code || "").trim().toUpperCase());
}
