import { C } from "../styles/theme";

export const MANGEL_KATEGORIEN = {
  OM: { label:"Ohne Mangel",         kurz:"OM", color:C.green,  bg:"rgba(15,194,138,0.12)",   border:"rgba(15,194,138,0.32)",  weight:0 },
  LM: { label:"Geringer Mangel",     kurz:"GM", color:C.blue,   bg:"rgba(75,140,247,0.12)",   border:"rgba(75,140,247,0.32)",  weight:1 },
  EM: { label:"Erheblicher Mangel",  kurz:"EM", color:C.amber,  bg:"rgba(245,166,32,0.12)",   border:"rgba(245,166,32,0.32)",  weight:2 },
  HM: { label:"Hauptmangel",         kurz:"HM", color:C.red,    bg:"rgba(240,69,90,0.12)",    border:"rgba(240,69,90,0.32)",   weight:3 },
  GM: { label:"Gefährlicher Mangel", kurz:"GF", color:C.purple, bg:"rgba(150,99,245,0.12)",   border:"rgba(150,99,245,0.32)",  weight:4 },
};

export const MANGEL_KATALOG = [
  /* 1 – Lenkanlage */
  { gruppe:"1 – Lenkanlage" },
  { code:"1.1.1", text:"Lenkrad: Übermäßiges Lenkungsspiel",                      kat:"HM" },
  { code:"1.1.2", text:"Lenkrad: Lenkrad lose / nicht sicher befestigt",            kat:"GM" },
  { code:"1.2.1", text:"Lenksäule: Schäden / Verbiegung der Lenksäule",             kat:"GM" },
  { code:"1.2.2", text:"Lenksäule: Kreuzkupplung/Gelenkwelle beschädigt",           kat:"GM" },
  { code:"1.3.1", text:"Lenkgetriebe: Undichtigkeit Lenkgetriebe",                  kat:"EM" },
  { code:"1.3.2", text:"Lenkgetriebe: Beschädigung Lenkgetriebegehäuse",            kat:"HM" },
  { code:"1.4.1", text:"Spurstangen: Spurstangenkopf beschädigt / zu viel Spiel",  kat:"GM" },
  { code:"1.4.2", text:"Spurstangen: Spurstange verbogen",                          kat:"GM" },
  { code:"1.5.1", text:"Servolenkung: Hydrauliköl zu niedrig / Leckage",            kat:"LM" },
  { code:"1.5.2", text:"Servolenkung: Schlauch / Leitung porös",                    kat:"EM" },
  /* 2 – Bremsanlage */
  { gruppe:"2 – Bremsanlage" },
  { code:"2.1.1", text:"Betriebsbremse: Ungleichmäßige Bremswirkung",               kat:"HM" },
  { code:"2.1.2", text:"Betriebsbremse: Bremswirkung unzureichend",                 kat:"HM" },
  { code:"2.1.3", text:"Betriebsbremse: Bremspedal ohne Widerstand",                kat:"GM" },
  { code:"2.2.1", text:"Bremsbeläge: Bremsbeläge stark verschlissen",               kat:"HM" },
  { code:"2.2.2", text:"Bremsbeläge: Bremsbelag-Verschleißwarner defekt",           kat:"LM" },
  { code:"2.3.1", text:"Bremsscheibe: Bremsscheibe stark verschlissen",             kat:"HM" },
  { code:"2.3.2", text:"Bremsscheibe: Bremsscheibe korrodiert / gerissen",          kat:"GM" },
  { code:"2.4.1", text:"Bremstrommel: Bremstrommel stark verschlissen",             kat:"HM" },
  { code:"2.5.1", text:"Bremsflüssigkeit: Wasseranteil zu hoch (> 3,5%)",           kat:"EM" },
  { code:"2.5.2", text:"Bremsflüssigkeit: Bremsflüssigkeitsstand kritisch niedrig", kat:"HM" },
  { code:"2.6.1", text:"Feststellbremse: Feststellbremse hält nicht ausreichend",   kat:"HM" },
  { code:"2.6.2", text:"Feststellbremse: Handbremshebel mechanisch beschädigt",     kat:"EM" },
  { code:"2.7.1", text:"ABS: ABS-Kontrollleuchte leuchtet",                         kat:"EM" },
  { code:"2.7.2", text:"ABS: ABS-Sensor defekt",                                    kat:"EM" },
  { code:"2.8.1", text:"Bremsleitung: Bremsleitung korrodiert / beschädigt",        kat:"GM" },
  { code:"2.8.2", text:"Bremsschlauch: Bremsschlauch porös / aufgequollen",         kat:"GM" },
  { code:"2.9.1", text:"Bremskraftverstärker: Unterdruck unzureichend",             kat:"HM" },
  /* 3 – Beleuchtung & Elektrik */
  { gruppe:"3 – Beleuchtung & Elektrik" },
  { code:"3.1.1", text:"Abblendlicht: Scheinwerfer links defekt",                   kat:"EM" },
  { code:"3.1.2", text:"Abblendlicht: Scheinwerfer rechts defekt",                  kat:"EM" },
  { code:"3.1.3", text:"Abblendlicht: Leuchtweitenregulierung defekt",              kat:"LM" },
  { code:"3.2.1", text:"Fernlicht: Fernlicht links defekt",                         kat:"LM" },
  { code:"3.2.2", text:"Fernlicht: Fernlicht rechts defekt",                        kat:"LM" },
  { code:"3.3.1", text:"Bremslicht: Bremslicht links defekt",                       kat:"HM" },
  { code:"3.3.2", text:"Bremslicht: Bremslicht rechts defekt",                      kat:"HM" },
  { code:"3.3.3", text:"Bremslicht: Drittes Bremslicht defekt",                     kat:"EM" },
  { code:"3.4.1", text:"Rücklicht: Rücklicht links defekt",                         kat:"EM" },
  { code:"3.4.2", text:"Rücklicht: Rücklicht rechts defekt",                        kat:"EM" },
  { code:"3.5.1", text:"Blinker: Fahrtrichtungsanzeiger vorne links defekt",        kat:"EM" },
  { code:"3.5.2", text:"Blinker: Fahrtrichtungsanzeiger vorne rechts defekt",       kat:"EM" },
  { code:"3.5.3", text:"Blinker: Fahrtrichtungsanzeiger hinten links defekt",       kat:"EM" },
  { code:"3.5.4", text:"Blinker: Fahrtrichtungsanzeiger hinten rechts defekt",      kat:"EM" },
  { code:"3.6.1", text:"Nebelscheinwerfer: Nebelscheinwerfer links defekt",         kat:"LM" },
  { code:"3.6.2", text:"Nebelscheinwerfer: Nebelscheinwerfer rechts defekt",        kat:"LM" },
  { code:"3.7.1", text:"Nebelschlussleuchte: Nebelschlussleuchte defekt",           kat:"EM" },
  { code:"3.8.1", text:"Kennzeichenbeleuchtung: Kennzeichenleuchte defekt",         kat:"LM" },
  { code:"3.9.1", text:"Tagfahrlicht: DRL nicht vorschriftsgemäß",                  kat:"LM" },
  { code:"3.10.1",text:"Warnblinkanlage: Warnblinkanlage defekt",                   kat:"EM" },
  { code:"3.11.1",text:"Hupe: Hupe defekt / nicht hörbar",                          kat:"LM" },
  { code:"3.12.1",text:"Batterie: Batterie defekt / tiefentladen",                  kat:"LM" },
  { code:"3.12.2",text:"Batterie: Batteriepole korrodiert / nicht gesichert",       kat:"LM" },
  { code:"3.13.1",text:"OBD: Motorleuchtwarnung (MIL) aktiv",                       kat:"EM" },
  { code:"3.13.2",text:"OBD: Fehlercodes sicherheitsrelevant",                      kat:"HM" },
  /* 4 – Räder & Reifen */
  { gruppe:"4 – Räder & Reifen" },
  { code:"4.1.1", text:"Profiltiefe: Profiltiefe unter 1,6 mm (gesetzliches Minimum)",kat:"HM" },
  { code:"4.1.2", text:"Profiltiefe: Profiltiefe 1,6–3 mm (Empfehlung: wechseln)",  kat:"EM" },
  { code:"4.2.1", text:"Reifenschäden: Seitenwand beschädigt / aufgeschnitten",     kat:"GM" },
  { code:"4.2.2", text:"Reifenschäden: Reifenwulst beschädigt",                     kat:"GM" },
  { code:"4.2.3", text:"Reifenschäden: Lauffläche: sichtbare Kordeln",              kat:"GM" },
  { code:"4.3.1", text:"Reifengröße: Falsche Reifenbreite oder -höhe",              kat:"EM" },
  { code:"4.3.2", text:"Reifengröße: Reifengröße nicht im Fahrzeugschein",          kat:"EM" },
  { code:"4.4.1", text:"Reifenalter: Reifen älter als 8 Jahre (DOT)",               kat:"EM" },
  { code:"4.4.2", text:"Reifenalter: Reifen älter als 10 Jahre",                    kat:"HM" },
  { code:"4.5.1", text:"Winterreifen: M+S-Reifen ohne Schneeflockensymbol",         kat:"LM" },
  { code:"4.6.1", text:"Felge: Felge verformt / gebrochen",                         kat:"GM" },
  { code:"4.6.2", text:"Felge: Felge stark korrodiert",                             kat:"EM" },
  { code:"4.7.1", text:"Reifendruck: Reifendruck zu niedrig",                       kat:"LM" },
  { code:"4.8.1", text:"Radmuttern: Radmuttern fehlen / nicht angezogen",           kat:"GM" },
  { code:"4.8.2", text:"Radschrauben: Radschraube beschädigt / gebrochen",          kat:"GM" },
  { code:"4.9.1", text:"Ersatzrad: Notrad / Reserverad nicht vorschriftsgemäß",     kat:"LM" },
  /* 5 – Karosserie & Rahmen */
  { gruppe:"5 – Karosserie & Rahmen" },
  { code:"5.1.1", text:"Rahmen: Starke Korrosion am Rahmen / Träger",               kat:"GM" },
  { code:"5.1.2", text:"Rahmen: Riss im Rahmen / Längsträger",                      kat:"GM" },
  { code:"5.2.1", text:"Karosserie: Scharfe Kanten durch Unfallschaden",            kat:"EM" },
  { code:"5.2.2", text:"Karosserie: Karosserie stark verrostet (tragend)",           kat:"GM" },
  { code:"5.3.1", text:"Motorhaube: Motorhaube öffnet sich während Fahrt",          kat:"GM" },
  { code:"5.3.2", text:"Motorhaube: Verriegelung defekt",                           kat:"HM" },
  { code:"5.4.1", text:"Türen: Türverriegelung defekt",                             kat:"EM" },
  { code:"5.4.2", text:"Türen: Tür schließt nicht sicher",                          kat:"HM" },
  { code:"5.5.1", text:"Stoßfänger: Stoßfänger fehlt",                              kat:"EM" },
  { code:"5.5.2", text:"Stoßfänger: Stoßfänger stark beschädigt",                   kat:"LM" },
  { code:"5.6.1", text:"Kennzeichen: Vorderes Kennzeichen fehlt / unleserlich",     kat:"HM" },
  { code:"5.6.2", text:"Kennzeichen: Hinteres Kennzeichen fehlt / unleserlich",     kat:"HM" },
  { code:"5.7.1", text:"Anhängerkupplung: AHK: Verriegelung defekt",                kat:"GM" },
  { code:"5.7.2", text:"Anhängerkupplung: AHK: Steckdose defekt",                   kat:"EM" },
  /* 6 – Abgasanlage & Umwelt */
  { gruppe:"6 – Abgasanlage & Umwelt" },
  { code:"6.1.1", text:"Abgasanlage: Undichtigkeit Abgasanlage",                    kat:"HM" },
  { code:"6.1.2", text:"Abgasanlage: Schalldämpfer locker / gebrochen",             kat:"HM" },
  { code:"6.2.1", text:"Abgaswerte: CO-Wert überschritten (Benziner)",              kat:"HM" },
  { code:"6.2.2", text:"Abgaswerte: HC-Wert überschritten",                         kat:"HM" },
  { code:"6.2.3", text:"Abgaswerte: NOx-Wert überschritten (Diesel)",               kat:"HM" },
  { code:"6.2.4", text:"Abgaswerte: Partikelgrenzwert überschritten",               kat:"HM" },
  { code:"6.3.1", text:"Ölverlust: Motoröl tropft",                                  kat:"HM" },
  { code:"6.3.2", text:"Ölverlust: Getriebeöl tropft",                              kat:"EM" },
  { code:"6.4.1", text:"Kraftstoff: Kraftstoffleck / Kraftstoffleitung beschädigt", kat:"GM" },
  { code:"6.4.2", text:"Kraftstoff: Tankdeckel fehlt / schließt nicht dicht",       kat:"EM" },
  { code:"6.5.1", text:"Katalysator: Katalysator fehlt oder beschädigt",            kat:"HM" },
  { code:"6.5.2", text:"Partikelfilter: DPF fehlt oder manipuliert",                kat:"GM" },
  { code:"6.6.1", text:"Kühlsystem: Kühlwasserverlust",                             kat:"EM" },
  { code:"6.6.2", text:"Kühlsystem: Kühlmittelstand kritisch niedrig",              kat:"HM" },
  /* 7 – Sicht & Windschutzscheibe */
  { gruppe:"7 – Sicht & Windschutzscheibe" },
  { code:"7.1.1", text:"Windschutzscheibe: Riss im Fahrerblickfeld",                kat:"HM" },
  { code:"7.1.2", text:"Windschutzscheibe: Riss außerhalb Fahrerblickfeld",         kat:"EM" },
  { code:"7.1.3", text:"Windschutzscheibe: Windschutzscheibe stark beschädigt",     kat:"GM" },
  { code:"7.2.1", text:"Scheibenwischer: Scheibenwischer vorne defekt",              kat:"EM" },
  { code:"7.2.2", text:"Scheibenwischer: Scheibenwischer hinten defekt",             kat:"LM" },
  { code:"7.2.3", text:"Scheibenwaschanlage: Waschanlage leer / defekt",            kat:"LM" },
  { code:"7.3.1", text:"Außenspiegel: Außenspiegel links fehlt",                     kat:"HM" },
  { code:"7.3.2", text:"Außenspiegel: Außenspiegel rechts fehlt",                    kat:"EM" },
  { code:"7.3.3", text:"Innenspiegel: Innenspiegel fehlt",                           kat:"LM" },
  { code:"7.4.1", text:"Sicht: Sichtbehinderung durch Aufkleber o.ä.",               kat:"HM" },
  /* 8 – Fahrwerk & Achsen */
  { gruppe:"8 – Fahrwerk & Achsen" },
  { code:"8.1.1", text:"Stoßdämpfer: Stoßdämpfer vorne defekt",                     kat:"EM" },
  { code:"8.1.2", text:"Stoßdämpfer: Stoßdämpfer hinten defekt",                    kat:"EM" },
  { code:"8.1.3", text:"Stoßdämpfer: Stoßdämpfer undicht (ölleckernd)",             kat:"EM" },
  { code:"8.2.1", text:"Federung: Feder gebrochen",                                  kat:"GM" },
  { code:"8.2.2", text:"Federung: Luftfederung: Undichtigkeit",                      kat:"EM" },
  { code:"8.3.1", text:"Achse: Achsschenkelbolzen zu viel Spiel",                   kat:"GM" },
  { code:"8.3.2", text:"Achse: Querlenker gerissen / beschädigt",                   kat:"GM" },
  { code:"8.4.1", text:"Stabilisator: Stabilisatorverbindung defekt",               kat:"EM" },
  { code:"8.5.1", text:"Radlager: Radlager: zu viel Spiel",                         kat:"HM" },
  { code:"8.5.2", text:"Radlager: Radlager: Geräusche (Lagerschaden)",              kat:"EM" },
  { code:"8.6.1", text:"Antriebswelle: Antriebswellenmanschette gerissen",           kat:"EM" },
  { code:"8.6.2", text:"Antriebswelle: Antriebswelle beschädigt",                   kat:"GM" },
  /* 9 – Sicherheitseinrichtungen */
  { gruppe:"9 – Sicherheitseinrichtungen" },
  { code:"9.1.1", text:"Sicherheitsgurt: Sicherheitsgurt fehlt / defekt vorne",     kat:"HM" },
  { code:"9.1.2", text:"Sicherheitsgurt: Sicherheitsgurt hinten defekt",            kat:"EM" },
  { code:"9.1.3", text:"Sicherheitsgurt: Gurtstrammer defekt",                      kat:"HM" },
  { code:"9.2.1", text:"Airbag: Airbag-Kontrollleuchte aktiv",                      kat:"EM" },
  { code:"9.3.1", text:"Warndreieck: Warndreieck fehlt",                            kat:"LM" },
  { code:"9.3.2", text:"Warnweste: Warnweste fehlt",                                kat:"LM" },
  { code:"9.3.3", text:"Verbandskasten: Verbandskasten fehlt / abgelaufen",         kat:"LM" },
  { code:"9.4.1", text:"Kindersitz: Kindersitzhalterung / ISOFIX defekt",           kat:"EM" },
  { code:"9.5.1", text:"ESP: ESP-Kontrollleuchte aktiv",                             kat:"EM" },
  { code:"9.5.2", text:"Reifendruckwarnsystem: RDKS-Kontrollleuchte aktiv",         kat:"LM" },
  /* 10 – Motor & Getriebe */
  { gruppe:"10 – Motor & Getriebe" },
  { code:"10.1.1",text:"Motor: Motorlagerung defekt / gerissen",                    kat:"GM" },
  { code:"10.2.1",text:"Getriebe: Getriebeöl tropft",                               kat:"EM" },
  { code:"10.2.2",text:"Getriebe: Getriebe springt aus dem Gang",                   kat:"HM" },
  { code:"10.3.1",text:"Kupplung: Kupplung schleift stark",                          kat:"EM" },
  { code:"10.4.1",text:"Motorsteuerung: ECU / Steuergerät meldet Fehler",           kat:"EM" },
  /* 11 – Spezifisch EV / Hybrid */
  { gruppe:"11 – Elektro / Hybrid (BEV/HEV)" },
  { code:"11.1.1",text:"Hochvoltbatterie: BMS-Fehler / Batteriefehler",             kat:"HM" },
  { code:"11.1.2",text:"Hochvoltbatterie: Kapazitätsverlust > 25%",                 kat:"EM" },
  { code:"11.2.1",text:"Ladesystem: Ladeport beschädigt",                            kat:"EM" },
  { code:"11.2.2",text:"Ladesystem: On-Board-Charger defekt",                        kat:"EM" },
  { code:"11.3.1",text:"Kabelbaum HV: HV-Leitungsschutz beschädigt",               kat:"GM" },
  { code:"11.4.1",text:"Regenerativbremse: Rekuperation außer Funktion",            kat:"LM" },
  /* 12 – LKW / Nutzfahrzeug-spezifisch */
  { gruppe:"12 – Nutzfahrzeug-spezifisch" },
  { code:"12.1.1",text:"Druckluftbremse: Druckluft-Leck",                           kat:"GM" },
  { code:"12.1.2",text:"Druckluftbremse: Druckaufbau zu langsam",                   kat:"HM" },
  { code:"12.2.1",text:"Fahrtenschreiber: Tachograph defekt / manipuliert",         kat:"HM" },
  { code:"12.2.2",text:"Fahrtenschreiber: Kalibrierung überfällig",                  kat:"EM" },
  { code:"12.3.1",text:"Ladungssicherung: Zurrösen beschädigt",                     kat:"EM" },
  { code:"12.4.1",text:"Hubladebühne: Hubladebühne defekt",                         kat:"EM" },
  { code:"12.5.1",text:"Geschwindigkeitsbegrenzer: Nicht kalibriert",               kat:"HM" },
];
